=== Dantas198/DWeb2019/TP2/pr.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT project-record (header, workteam, abstract, deliverables, date) >
<!ELEMENT date (#PCDATA) >

<!ELEMENT header (key-name, title, subtitle?, begin-date, end-date, supervisor) >
<!ELEMENT key-name (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin-date (#PCDATA) >
<!ELEMENT end-date (#PCDATA) >
<!ELEMENT supervisor (link) > 
<!ELEMENT link (#PCDATA) >

<!ELEMENT workteam (element+) >
<!ELEMENT element (name, number, email, github) >
<!ELEMENT github (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT number (#PCDATA) >
<!ELEMENT email (#PCDATA) >

<!ELEMENT abstract (p*) >
<!ELEMENT p (#PCDATA|link|italic|bold)* >
<!ELEMENT italic (#PCDATA) >
<!ELEMENT bold (#PCDATA) >

<!ELEMENT deliverables (link*) >

<!ATTLIST link
            url CDATA #REQUIRED >

=== Dantas198/DWeb2019/TP2/PR.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project-record SYSTEM "pr.dtd">
<project-record>
    <header>
        <key-name></key-name>
        <title>TP2</title>
        <begin-date>Setembro 2019</begin-date>
        <end-date>Setembro 2019</end-date>
        <supervisor>
            <link url="www.di.uminho.pt/~jcr">José Carlos Ramalho</link>
        </supervisor>
    </header>
    <workteam>
        <element>
            <name>Marco Filipe Leitão Dantas</name>
            <number>81736</number>
            <email>a81736@alunos.uminho.pt</email>
            <github>https://github.com/Dantas198</github>
        </element>
    </workteam>
    <abstract>
        <p>Preenchimento de um project-record e definição do seu dtd</p>
        <p>Resolução dos exercícios 6 e 7 <link url="http://www4.di.uminho.pt/~jcr/XML/CURSOS/PED2008/fichas/ficha3/index.html">ficha 3</link> relativos a DTD's e XPATH</p>
    </abstract>
    <deliverables>
        <link url="pr.dtd">documento dtd do project-record</link>
        <link url="arq.dtd">Resolução do exercício 7 (ficha3)</link>
        <link url="arq.txt">Resolução do exercício 6 (ficha3)</link>
    </deliverables>
    <date>29-09-2019</date>
</project-record>
